# Generated by Django 2.2.12 on 2020-10-23 16:21

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0002_group_volunteer_found'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='volunteered',
            field=otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, null=True),
        ),
    ]
